name: 'Deploy GCP function gpz-convert-ids'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'functions/convert_ids/convert_ids_deploy/**'

jobs:
  deploy-convert-ids-func:
    uses: ./.github/workflows/helper-deploy-func.yaml
    with:
      func-name: "gpz-convert-ids"
      func-src-dir: "functions/convert_ids/convert_ids_deploy"
      func-entrypoint: "convert_ids"
      func-memory-mb: 1024
      func-data-gcs-url: "gs://geneplexus-func-data/convert-ids/convert-ids_data.tar.gz"
    secrets: inherit
