name: Deploy Cloud Functions
on:
  push:
    branches:
      - main
    paths:
      - 'functions/ml/ml_deploy/**'

jobs:
  deploy-ml-func:
    uses: ./.github/workflows/helper-deploy-func.yaml
    with:
      func-name: "gpz-ml"
      func-src-dir: "functions/ml/ml_deploy"
      func-entrypoint: "run_pipeline"
      func-memory-mb: 8192
      func-data-gcs-url: "gs://geneplexus-func-data/ml/ml_data.tar.gz"
    permissions:
      contents: 'read'
      id-token: 'write'
    secrets: inherit
