name: Test Frontend

on: pull_request

defaults:
  run:
    working-directory: ./frontend

jobs:
  # test that app can build without issues
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run build

  # test that app has no typescript errors
  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run test:types

  # test that app is properly formatted and linted
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install

      - if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Run test
        run: bun run test:lint
